fix:

diff --git a/.github/workflows/tp-node.yaml b/.github/workflows/tp-node.yaml
--- a/.github/workflows/tp-node.yaml
+++ b/.github/workflows/tp-node.yaml
@@ -1,4 +1,4 @@
-name: exo_angular
+name: tp_node
 on:
   push:
     branches: [features/*, hotfix/*]
@@ -43,14 +43,16 @@ jobs:
           node-version: ${{ matrix.version }}
 
       # Le test de node fait une erreur ce qui fait sortir du workflow et m'empêche de créer un artefact
+      # donc je pass outre l'erreur, l'enregistre et la trigger quand j'ai fini de faire l'artefact
       - name: Test de node v${{ matrix.version }} et création de l'artefact
-        run: npm test > test_output.txt 2>&1
+        run: npm test > test_output.txt 2>&1 || echo "::set-output name=error::true"
         continue-on-error: true
+        id: npm-test
 
       - name: Création de l'artefact
         uses: actions/upload-artifact@v3
         with:
-          name: npm-test-result
+          name: test_output
           path: test_output.txt
 
       - name: Téléchargement artefact
@@ -60,3 +62,7 @@ jobs:
 
       - name: Lecture de l'artefact
         run: cat test_output.txt
+
+      - name: Arrêt si erreur lors du test
+        if: steps.npm-test.outputs.error == true
+        run: exit 1
