fix:

diff --git a/.github/workflows/tp-node.yaml b/.github/workflows/tp-node.yaml
--- a/.github/workflows/tp-node.yaml
+++ b/.github/workflows/tp-node.yaml
@@ -45,8 +45,8 @@ jobs:
       # Le test de node fait une erreur ce qui fait sortir du workflow et m'empêche de créer un artefact
       # donc je pass outre l'erreur, l'enregistre et la trigger quand j'ai fini de faire l'artefact
       - name: Test de node v${{ matrix.version }} et création de l'artefact
-        run: npm test > test_output.txt 2>&1 || echo "::set-output name=error::true"
-        continue-on-error: true
+        run: npm test > test_output.txt 2>&1 || echo "error=true" >> $GITHUB_OUTPUT
+        # continue-on-error: true
         id: npm-test
 
       - name: Création de l'artefact
